---
# Set the kubelet config files
- name: Set Kubelet Config
  hosts: kubernetes
  become: yes
  tasks:
    - name: Replace kubelet service file
      copy:
        src: ../templates/etc/systemd/system/kubelet.service.d/10-kubeadm.conf.j2
        dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    
    - name: Replace kubelet config file
      copy:
        src: ../var/lib/kubelet/config.yaml.j2
        dest: /var/lib/kubelet/config.yaml

    - name: Reload systemd
      systemd:
        daemon_reload: yes
    
    - name: Restart kubelet
      systemd:
        name: kubelet
        state: restarted
        enabled: yes
