---
# Config GPU nodes
- name: Install GPU requirements
  hosts: gpu_nodes
  become: yes
  tasks:
    - name: Add NVIDIA GPG key
      command: curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

    - name: Add NVIDIA container toolkit repository
      command: curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: Install NVIDIA toolkit
      apt:
        name: nvidia-container-toolkit
        state: present
        update_cache: yes

    - name: Configure container runtime
      command: nvidia-container-runtime configure --runtime=containerd --force

    - name: Update containerd config to set default_runtime_name to nvidia
      lineinfile:
      path: /etc/containerd/config.toml
      regexp: '^(\s*default_runtime_name\s*=\s*).*'
      line: 'default_runtime_name = "nvidia"'
      state: present

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart containerd
      service:
        name: containerd
        state: restarted
        enabled: yes
    
    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted
        enabled: yes
