---
# Install Containerd and Configuration
- name: Install Containerd
  hosts: kubernetes
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: yes

    - name: Install Containerd
      apt:
        name:
          - containerd
        state: present
    
    - name: Create Containerd config directory
      file:
        path: /etc/containerd
        state: directory

    - name: Generate default Containerd config
      shell: 'containerd config default | tee /etc/containerd/config.toml'

    - name: Set systemd cgroup driver in Containerd
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Restart Containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes
