- name: Install Kubernetes Components
  hosts: kubernetes
  become: yes
  tasks:
    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold Kubernetes packages at current version
      command: apt-mark hold kubelet kubeadm kubectl

    - name: Restart Kubelet
      systemd:
        name: kubelet
        state: restarted
        enabled: yes
