- name: Install Kubernetes Components
  hosts: kubernetes
  become: yes
  tasks:
    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold Kubernetes packages at current version
      command: apt-mark hold kubelet kubeadm kubectl

    - name: Disable swap (required for Kubernetes)
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Remove swap entry from fstab
      replace:
        path: /etc/fstab
        regexp: '(^.*swap.*$)'
        replace: '# \1'

    - name: Restart Kubelet
      systemd:
        name: kubelet
        state: restarted
        enabled: yes
