---
# Install Containerd and Configuration
- name: Install Containerd
  hosts: kubernetes
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: yes

    - name: Install Containerd
      apt:
        name:
          - containerd
        state: present
    
    - name: Create Containerd config directory
      file:
        path: /etc/containerd
        state: directory

    - name: Copy Containerd config
      copy:
        src: ../templates/etc/containerd/config.toml.js
        dest: /etc/containerd/config.toml

    - name: Set systemd cgroup driver in Containerd
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart Containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes
