- name: Get Join Command
  hosts: control_plane
  become: yes
  tasks:
    - name: Retrieve Join Command
      command: kubeadm token create --print-join-command --cri-socket=unix:///run/containerd/containerd.sock
      register: join_command

    - name: Save Join Command
      set_fact:
        kube_join_command: "{{ join_command.stdout }}"

- name: Join Workers to Cluster
  hosts: workers
  become: yes
  tasks:
    - name: Join Kubernetes Cluster
      command: "{{ hostvars['master'].kube_join_command }}"
